data = {'Milwaukee': {'team_url': 'https://en.wikipedia.org//wiki/2019%E2%80%9320_Milwaukee_Bucks_season',
                      'players': {
                          'Antetokounmpo, Giannis': {'url': 'https://en.wikipedia.org/wiki/Giannis_Antetokounmpo', 'stats': {'PPG': 29.5, 'BPG': 1.0, 'RPG': 13.6}},
                          'Antetokounmpo, Thanasis': {'url': 'https://en.wikipedia.org/wiki/Thanasis_Antetokounmpo', 'stats': {'PPG': 2.8, 'BPG': 0.1, 'RPG': 1.2}},
                          'Bledsoe, Eric': {'url': 'https://en.wikipedia.org/wiki/Eric_Bledsoe', 'stats': {'PPG': 14.9, 'BPG': 0.4, 'RPG': 4.6}},
                          'Brown, Sterling': {'url': 'https://en.wikipedia.org/wiki/Sterling_Brown_(basketball)', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                          'Connaughton, Pat': {'url': 'https://en.wikipedia.org/wiki/Pat_Connaughton', 'stats': {'PPG': 5.4, 'BPG': 0.5, 'RPG': 4.2}},
                          'DiVincenzo, Donte': {'url': 'https://en.wikipedia.org/wiki/Donte_DiVincenzo', 'stats': {'PPG': 9.2, 'BPG': 0.3, 'RPG': 4.8}},
                          'Hill, George': {'url': 'https://en.wikipedia.org/wiki/George_Hill_(basketball)', 'stats': {'PPG': 9.4, 'BPG': 0.1, 'RPG': 3.0}},
                          'İlyasova, Ersan': {'url': 'https://en.wikipedia.org/wiki/Ersan_%C4%B0lyasova', 'stats': {'PPG': 6.6, 'BPG': 0.3, 'RPG': 4.8}},
                          'Korver, Kyle': {'url': 'https://en.wikipedia.org/wiki/Kyle_Korver', 'stats': {'PPG': 6.7, 'BPG': 0.2, 'RPG': 2.1}},
                          'Lopez, Brook': {'url': 'https://en.wikipedia.org/wiki/Brook_Lopez', 'stats': {'PPG': 12.0, 'BPG': 2.4, 'RPG': 4.6}},
                          'Lopez, Robin': {'url': 'https://en.wikipedia.org/wiki/Robin_Lopez', 'stats': {'PPG': 5.4, 'BPG': 0.7, 'RPG': 2.4}},
                          'Mason, Frank': {'url': 'https://en.wikipedia.org/wiki/Frank_Mason_III', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                          'Matthews, Wesley': {'url': 'https://en.wikipedia.org/wiki/Wesley_Matthews', 'stats': {'PPG': 7.4, 'BPG': 0.1, 'RPG': 2.5}},
                          'Middleton, Khris': {'url': 'https://en.wikipedia.org/wiki/Khris_Middleton', 'stats': {'PPG': 20.9, 'BPG': 0.1, 'RPG': 6.2}},
                          'Reynolds, Cameron': {'url': 'https://en.wikipedia.org/wiki/Cameron_Reynolds', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                          'Williams, Marvin': {'url': 'https://en.wikipedia.org/wiki/Marvin_Williams', 'stats': {'PPG': 6.7, 'BPG': 0.5, 'RPG': 2.7}},
                          'Wilson, D. J.': {'url': 'https://en.wikipedia.org/wiki/D._J._Wilson', 'stats': {'PPG': 3.6, 'BPG': 0.1, 'RPG': 2.5}}}},
        'Miami': {'team_url': 'https://en.wikipedia.org//wiki/2019%E2%80%9320_Miami_Heat_season',
                  'players': {'Adebayo, Bam': {'url': 'https://en.wikipedia.org/wiki/Bam_Adebayo', 'stats': {'PPG': 15.9, 'BPG': 1.3, 'RPG': 10.2}},
                              'Alexander, Kyle': {'url': 'https://en.wikipedia.org/wiki/Kyle_Alexander', 'stats': {'PPG': 1.0, 'BPG': 0.0, 'RPG': 1.5}},
                              'Butler, Jimmy': {'url': 'https://en.wikipedia.org/wiki/Jimmy_Butler', 'stats': {'PPG': 19.9, 'BPG': 0.6, 'RPG': 6.7}},
                              'Crowder, Jae': {'url': 'https://en.wikipedia.org/wiki/Jae_Crowder', 'stats': {'PPG': 9.9, 'BPG': 0.3, 'RPG': 6.2}},
                              'Dragić, Goran': {'url': 'https://en.wikipedia.org/wiki/Goran_Dragi%C4%87', 'stats': {'PPG': 16.2, 'BPG': 0.2, 'RPG': 3.2}},
                              'Haslem, Udonis': {'url': 'https://en.wikipedia.org/wiki/Udonis_Haslem', 'stats': {'PPG': 3.0, 'BPG': 0.0, 'RPG': 4.0}},
                              'Herro, Tyler': {'url': 'https://en.wikipedia.org/wiki/Tyler_Herro', 'stats': {'PPG': 13.5, 'BPG': 0.2, 'RPG': 4.1}},
                              'Hill, Solomon': {'url': 'https://en.wikipedia.org/wiki/Solomon_Hill_(basketball)', 'stats': {'PPG': 5.7, 'BPG': 0.1, 'RPG': 3.0}},
                              'Iguodala, Andre': {'url': 'https://en.wikipedia.org/wiki/Andre_Iguodala', 'stats': {'PPG': 4.6, 'BPG': 1.0, 'RPG': 3.7}},
                              'Jones, Derrick': {'url': 'https://en.wikipedia.org/wiki/Derrick_Jones_Jr.', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                              'Leonard, Meyers': {'url': 'https://en.wikipedia.org/wiki/Meyers_Leonard', 'stats': {'PPG': 6.1, 'BPG': 0.3, 'RPG': 5.1}},
                              'Nunn, Kendrick': {'url': 'https://en.wikipedia.org/wiki/Kendrick_Nunn', 'stats': {'PPG': 15.3, 'BPG': 0.2, 'RPG': 2.7}},
                              'Okpala, KZ': {'url': 'https://en.wikipedia.org/wiki/KZ_Okpala', 'stats': {'PPG': 1.4, 'BPG': 0.2, 'RPG': 1.0}},
                              'Olynyk, Kelly': {'url': 'https://en.wikipedia.org/wiki/Kelly_Olynyk', 'stats': {'PPG': 8.2, 'BPG': 0.3, 'RPG': 4.6}},
                              'Robinson, Duncan': {'url': 'https://en.wikipedia.org/wiki/Duncan_Robinson_(basketball)', 'stats': {'PPG': 13.5, 'BPG': 0.3, 'RPG': 3.2}},
                              'Silva, Chris': {'url': 'https://en.wikipedia.org/wiki/Chris_Silva', 'stats': {'PPG': 3.0, 'BPG': 0.5, 'RPG': 2.9}},
                              'Vincent, Gabe': {'url': 'https://en.wikipedia.org/wiki/Gabe_Vincent', 'stats': {'PPG': 2.4, 'BPG': 0.0, 'RPG': 0.6}}}},
        'Boston': {'team_url': 'https://en.wikipedia.org//wiki/2019%E2%80%9320_Boston_Celtics_season',
                   'players': {'Brown, Jaylen': {'url': 'https://en.wikipedia.org/wiki/Jaylen_Brown', 'stats': {'PPG': 20.3, 'BPG': 0.4, 'RPG': 6.4}},
                               'Edwards, Carsen': {'url': 'https://en.wikipedia.org/wiki/Carsen_Edwards', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                               'Fall, Tacko': {'url': 'https://en.wikipedia.org/wiki/Tacko_Fall', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                               'Green, Javonte': {'url': 'https://en.wikipedia.org/wiki/Javonte_Green', 'stats': {'PPG': 3.4, 'BPG': 0.2, 'RPG': 1.9}},
                               'Hayward, Gordon': {'url': 'https://en.wikipedia.org/wiki/Gordon_Hayward', 'stats': {'PPG': 17.5, 'BPG': 0.4, 'RPG': 6.7}},
                               'Kanter, Enes': {'url': 'https://en.wikipedia.org/wiki/Enes_Kanter', 'stats': {'PPG': 8.1, 'BPG': 0.7, 'RPG': 7.4}},
                               'Langford, Romeo': {'url': 'https://en.wikipedia.org/wiki/Romeo_Langford', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                               'Ojeleye, Semi': {'url': 'https://en.wikipedia.org/wiki/Semi_Ojeleye', 'stats': {'PPG': 3.4, 'BPG': 0.1, 'RPG': 2.1}},
                               'Poirier, Vincent': {'url': 'https://en.wikipedia.org/wiki/Vincent_Poirier', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                               'Smart, Marcus': {'url': 'https://en.wikipedia.org/wiki/Marcus_Smart', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                               'Tatum, Jayson': {'url': 'https://en.wikipedia.org/wiki/Jayson_Tatum', 'stats': {'PPG': 23.4, 'BPG': 0.9, 'RPG': 7.0}},
                               'Theis, Daniel': {'url': 'https://en.wikipedia.org/wiki/Daniel_Theis', 'stats': {'PPG': 9.2, 'BPG': 1.3, 'RPG': 6.6}},
                               'Walker, Kemba': {'url': 'https://en.wikipedia.org/wiki/Kemba_Walker', 'stats': {'PPG': 20.4, 'BPG': 0.5, 'RPG': 3.9}},
                               'Wanamaker, Brad': {'url': 'https://en.wikipedia.org/wiki/Brad_Wanamaker', 'stats': {'PPG': 6.9, 'BPG': 0.2, 'RPG': 2.0}},
                               'Waters, Tremont': {'url': 'https://en.wikipedia.org/wiki/Tremont_Waters', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                               'Williams, Grant': {'url': 'https://en.wikipedia.org/wiki/Grant_Williams_(basketball)', 'stats': {'PPG': 3.4, 'BPG': 0.5, 'RPG': 2.6}},
                               'Williams, Robert': {'url': 'https://en.wikipedia.org/wiki/Robert_Williams_(basketball)', 'stats': {'PPG': 5.2, 'BPG': 1.2, 'RPG': 4.4}}}},
        'Toronto': {'team_url': 'https://en.wikipedia.org//wiki/2019%E2%80%9320_Toronto_Raptors_season',
                    'players': {'Anunoby, OG': {'url': 'https://en.wikipedia.org/wiki/OG_Anunoby', 'stats': {'PPG': 10.6, 'BPG': 0.7, 'RPG': 5.3}},
                                'Boucher, Chris': {'url': 'https://en.wikipedia.org/wiki/Chris_Boucher_(basketball)', 'stats': {'PPG': 6.6, 'BPG': 1.0, 'RPG': 4.5}},
                                'Brissett, Oshae': {'url': 'https://en.wikipedia.org/wiki/Oshae_Brissett', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                                'Davis, Terence': {'url': 'https://en.wikipedia.org/wiki/Terence_Davis', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                                'Gasol, Marc': {'url': 'https://en.wikipedia.org/wiki/Marc_Gasol', 'stats': {'PPG': 7.5, 'BPG': 0.9, 'RPG': 6.3}},
                                'Hernandez, Dewan': {'url': 'https://en.wikipedia.org/wiki/Dewan_Hernandez', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                                'Hollis-Jefferson, Rondae': {'url': 'https://en.wikipedia.org/wiki/Rondae_Hollis-Jefferson', 'stats': {'PPG': 7.0, 'BPG': 0.4, 'RPG': 4.7}},
                                'Ibaka, Serge': {'url': 'https://en.wikipedia.org/wiki/Serge_Ibaka', 'stats': {'PPG': 15.4, 'BPG': 0.8, 'RPG': 8.2}},
                                'Johnson, Stanley': {'url': 'https://en.wikipedia.org/wiki/Stanley_Johnson_(basketball)', 'stats': {'PPG': 2.4, 'BPG': 0.2, 'RPG': 1.5}},
                                'Lowry, Kyle': {'url': 'https://en.wikipedia.org/wiki/Kyle_Lowry', 'stats': {'PPG': 19.4, 'BPG': 0.4, 'RPG': 5.0}},
                                'McCaw, Patrick': {'url': 'https://en.wikipedia.org/wiki/Patrick_McCaw', 'stats': {'PPG': 4.6, 'BPG': 0.1, 'RPG': 2.3}},
                                'Miller, Malcolm': {'url': 'https://en.wikipedia.org/wiki/Malcolm_Miller_(basketball)', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                                'Powell, Norman': {'url': 'https://en.wikipedia.org/wiki/Norman_Powell', 'stats': {'PPG': 16.0, 'BPG': 0.4, 'RPG': 3.7}},
                                'Siakam, Pascal': {'url': 'https://en.wikipedia.org/wiki/Pascal_Siakam', 'stats': {'PPG': 22.9, 'BPG': 0.9, 'RPG': 7.3}},
                                'Thomas, Matt': {'url': 'https://en.wikipedia.org/wiki/Matt_Thomas_(basketball)', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                                'VanVleet, Fred': {'url': 'https://en.wikipedia.org/wiki/Fred_VanVleet', 'stats': {'PPG': 17.6, 'BPG': 0.3, 'RPG': 3.8}},
                                'Watson, Paul': {'url': 'https://en.wikipedia.org/wiki/Paul_Watson_(basketball)', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}}}},
        'LA Lakers': {'team_url': 'https://en.wikipedia.org//wiki/2019%E2%80%9320_Los_Angeles_Lakers_season',
                      'players': {'Antetokounmpo, Kostas': {'url': 'https://en.wikipedia.org/wiki/Kostas_Antetokounmpo', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                                  'Bradley, Avery': {'url': 'https://en.wikipedia.org/wiki/Avery_Bradley', 'stats': {'PPG': 8.6, 'BPG': 0.1, 'RPG': 2.3}},
                                  'Cacok, Devontae': {'url': 'https://en.wikipedia.org/wiki/Devontae_Cacok', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                                  'Caldwell-Pope, Kentavious': {'url': 'https://en.wikipedia.org/wiki/Kentavious_Caldwell-Pope', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                                  'Caruso, Alex': {'url': 'https://en.wikipedia.org/wiki/Alex_Caruso', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                                  'Cook, Quinn': {'url': 'https://en.wikipedia.org/wiki/Quinn_Cook', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                                  'Davis, Anthony': {'url': 'https://en.wikipedia.org/wiki/Anthony_Davis', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                                  'Dudley, Jared': {'url': 'https://en.wikipedia.org/wiki/Jared_Dudley', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                                  'Green, Danny': {'url': 'https://en.wikipedia.org/wiki/Danny_Green_(basketball)', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                                  'Horton-Tucker, Talen': {'url': 'https://en.wikipedia.org/wiki/Talen_Horton-Tucker', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                                  'Howard, Dwight': {'url': 'https://en.wikipedia.org/wiki/Dwight_Howard', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                                  'James, LeBron': {'url': 'https://en.wikipedia.org/wiki/LeBron_James', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                                  'Kuzma, Kyle': {'url': 'https://en.wikipedia.org/wiki/Kyle_Kuzma', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                                  'McGee, JaVale': {'url': 'https://en.wikipedia.org/wiki/JaVale_McGee', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                                  'Morris, Markieff': {'url': 'https://en.wikipedia.org/wiki/Markieff_Morris', 'stats': {'PPG': 11.0, 'BPG': 0.3, 'RPG': 3.9}},
                                  'Rondo, Rajon': {'url': 'https://en.wikipedia.org/wiki/Rajon_Rondo', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                                  'Smith, J. R.': {'url': 'https://en.wikipedia.org/wiki/J._R._Smith', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                                  'Waiters, Dion': {'url': 'https://en.wikipedia.org/wiki/Dion_Waiters', 'stats': {'PPG': 9.3, 'BPG': 0.7, 'RPG': 3.7}}}},
        'Houston': {'team_url': 'https://en.wikipedia.org//wiki/2019%E2%80%9320_Houston_Rockets_season',
                    'players': {'Caboclo, Bruno': {'url': 'https://en.wikipedia.org/wiki/Bruno_Caboclo', 'stats': {'PPG': 2.8, 'BPG': 0.5, 'RPG': 2.0}},
                                'Carroll, DeMarre': {'url': 'https://en.wikipedia.org/wiki/DeMarre_Carroll', 'stats': {'PPG': 2.2, 'BPG': 0.1, 'RPG': 2.1}},
                                'Chandler, Tyson': {'url': 'https://en.wikipedia.org/wiki/Tyson_Chandler', 'stats': {'PPG': 1.3, 'BPG': 0.3, 'RPG': 2.5}},
                                'Clemons, Chris': {'url': 'https://en.wikipedia.org/wiki/Chris_Clemons_(basketball)', 'stats': {'PPG': 4.9, 'BPG': 0.1, 'RPG': 0.9}},
                                'Covington, Robert': {'url': 'https://en.wikipedia.org/wiki/Robert_Covington', 'stats': {'PPG': 12.8, 'BPG': 0.9, 'RPG': 6.0}},
                                'Frazier, Michael': {'url': 'https://en.wikipedia.org/wiki/Michael_Frazier_II', 'stats': {'PPG': 2.1, 'BPG': 0, 'RPG': 0}},
                                'Gordon, Eric': {'url': 'https://en.wikipedia.org/wiki/Eric_Gordon', 'stats': {'PPG': 14.4, 'BPG': 0.3, 'RPG': 2.0}},
                                'Green, Jeff': {'url': 'https://en.wikipedia.org/wiki/Jeff_Green_(basketball)', 'stats': {'PPG': 7.8, 'BPG': 0.3, 'RPG': 2.7}},
                                'Harden, James': {'url': 'https://en.wikipedia.org/wiki/James_Harden', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                                'House, Danuel': {'url': 'https://en.wikipedia.org/wiki/Danuel_House', 'stats': {'PPG': 10.5, 'BPG': 0.5, 'RPG': 4.2}},
                                'Mbah a Moute, Luc': {'url': 'https://en.wikipedia.org/wiki/Luc_Mbah_a_Moute', 'stats': {'PPG': 1.7, 'BPG': 0, 'RPG': 0}},
                                'McLemore, Ben': {'url': 'https://en.wikipedia.org/wiki/Ben_McLemore', 'stats': {'PPG': 10.1, 'BPG': 0.2, 'RPG': 2.2}},
                                'Nwaba, David': {'url': 'https://en.wikipedia.org/wiki/David_Nwaba', 'stats': {'PPG': 5.2, 'BPG': 0.6, 'RPG': 2.3}},
                                'Rivers, Austin': {'url': 'https://en.wikipedia.org/wiki/Austin_Rivers', 'stats': {'PPG': 8.8, 'BPG': 0.1, 'RPG': 2.6}},
                                'Sefolosha, Thabo': {'url': 'https://en.wikipedia.org/wiki/Thabo_Sefolosha', 'stats': {'PPG': 2.2, 'BPG': 0.3, 'RPG': 2.3}},
                                'Tucker, P. J.': {'url': 'https://en.wikipedia.org/wiki/P._J._Tucker', 'stats': {'PPG': 6.9, 'BPG': 0.5, 'RPG': 6.6}},
                                'Westbrook, Russell': {'url': 'https://en.wikipedia.org/wiki/Russell_Westbrook', 'stats': {'PPG': 27.2, 'BPG': 0.4, 'RPG': 7.9}}}},
        'Denver': {'team_url': 'https://en.wikipedia.org//wiki/2019%E2%80%9320_Denver_Nuggets_season',
                   'players': {'Barton, Will': {'url': 'https://en.wikipedia.org/wiki/Will_Barton', 'stats': {'PPG': 15.1, 'BPG': 0.5, 'RPG': 6.3}},
                               'Bates-Diop, Keita': {'url': 'https://en.wikipedia.org/wiki/Keita_Bates-Diop', 'stats': {'PPG': 6.8, 'BPG': 0.5, 'RPG': 3.0}},
                               'Bol, Bol': {'url': 'https://en.wikipedia.org/wiki/Bol_Bol', 'stats': {'PPG': 5.7, 'BPG': 0.9, 'RPG': 2.7}},
                               'Čančar, Vlatko': {'url': 'https://en.wikipedia.org/wiki/Vlatko_%C4%8Can%C4%8Dar', 'stats': {'PPG': 1.2, 'BPG': 0.1, 'RPG': 0.7}},
                               'Cook, Tyler': {'url': 'https://en.wikipedia.org/wiki/Tyler_Cook', 'stats': {'PPG': 1.7, 'BPG': 0.0, 'RPG': 0.9}},
                               'Craig, Torrey': {'url': 'https://en.wikipedia.org/wiki/Torrey_Craig', 'stats': {'PPG': 5.4, 'BPG': 0.6, 'RPG': 3.3}},
                               'Daniels, Troy': {'url': 'https://en.wikipedia.org/wiki/Troy_Daniels', 'stats': {'PPG': 4.2, 'BPG': 0.1, 'RPG': 1.1}},
                               'Dozier, PJ': {'url': 'https://en.wikipedia.org/wiki/PJ_Dozier', 'stats': {'PPG': 5.8, 'BPG': 0.2, 'RPG': 1.9}},
                               'Grant, Jerami': {'url': 'https://en.wikipedia.org/wiki/Jerami_Grant', 'stats': {'PPG': 12.0, 'BPG': 0.8, 'RPG': 3.5}},
                               'Harris, Gary': {'url': 'https://en.wikipedia.org/wiki/Gary_Harris', 'stats': {'PPG': 10.4, 'BPG': 0.3, 'RPG': 2.9}},
                               'Jokić, Nikola': {'url': 'https://en.wikipedia.org/wiki/Nikola_Joki%C4%87', 'stats': {'PPG': 19.9, 'BPG': 0.6, 'RPG': 9.7}},
                               'Millsap, Paul': {'url': 'https://en.wikipedia.org/wiki/Paul_Millsap', 'stats': {'PPG': 11.6, 'BPG': 0.6, 'RPG': 5.7}},
                               'Morris, Monté': {'url': 'https://en.wikipedia.org/wiki/Mont%C3%A9_Morris', 'stats': {'PPG': 9.0, 'BPG': 0.2, 'RPG': 1.9}},
                               'Murray, Jamal': {'url': 'https://en.wikipedia.org/wiki/Jamal_Murray', 'stats': {'PPG': 18.5, 'BPG': 0.3, 'RPG': 4.0}},
                               'Plumlee, Mason': {'url': 'https://en.wikipedia.org/wiki/Mason_Plumlee', 'stats': {'PPG': 7.2, 'BPG': 0.6, 'RPG': 5.2}},
                               'Porter, Michael': {'url': 'https://en.wikipedia.org/wiki/Michael_Porter_Jr.', 'stats': {'PPG': 9.3, 'BPG': 0.5, 'RPG': 4.7}},
                               'Vonleh, Noah': {'url': 'https://en.wikipedia.org/wiki/Noah_Vonleh', 'stats': {'PPG': 4.1, 'BPG': 0.2, 'RPG': 4.0}}}},
        'LA Clippers': {'team_url': 'https://en.wikipedia.org//wiki/2019%E2%80%9320_Los_Angeles_Clippers_season',
                        'players': {'Beverley, Patrick': {'url': 'https://en.wikipedia.org/wiki/Patrick_Beverley', 'stats': {'PPG': 7.9, 'BPG': 0.5, 'RPG': 5.2}},
                                    'Coffey, Amir': {'url': 'https://en.wikipedia.org/wiki/Amir_Coffey', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                                    'George, Paul': {'url': 'https://en.wikipedia.org/wiki/Paul_George', 'stats': {'PPG': 21.5, 'BPG': 0.4, 'RPG': 5.2}},
                                    'Green, JaMychal': {'url': 'https://en.wikipedia.org/wiki/JaMychal_Green', 'stats': {'PPG': 6.8, 'BPG': 0.4, 'RPG': 6.2}},
                                    'Harrell, Montrezl': {'url': 'https://en.wikipedia.org/wiki/Montrezl_Harrell', 'stats': {'PPG': 18.6, 'BPG': 1.1, 'RPG': 7.1}},
                                    'Jackson, Reggie': {'url': 'https://en.wikipedia.org/wiki/Reggie_Jackson_(basketball,_born_1990)', 'stats': {'PPG': 14.9, 'BPG': 0.1, 'RPG': 2.9}},
                                    'Kabengele, Mfiondu': {'url': 'https://en.wikipedia.org/wiki/Mfiondu_Kabengele', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                                    'Leonard, Kawhi': {'url': 'https://en.wikipedia.org/wiki/Kawhi_Leonard', 'stats': {'PPG': 27.1, 'BPG': 0.6, 'RPG': 7.1}},
                                    'Mann, Terance': {'url': 'https://en.wikipedia.org/wiki/Terance_Mann', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                                    'McGruder, Rodney': {'url': 'https://en.wikipedia.org/wiki/Rodney_McGruder', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                                    'Morris, Marcus': {'url': 'https://en.wikipedia.org/wiki/Marcus_Morris', 'stats': {'PPG': 19.6, 'BPG': 0.4, 'RPG': 5.4}},
                                    'Motley, Johnathan': {'url': 'https://en.wikipedia.org/wiki/Johnathan_Motley', 'stats': {'PPG': 0, 'BPG': 0, 'RPG': 0}},
                                    'Noah, Joakim': {'url': 'https://en.wikipedia.org/wiki/Joakim_Noah', 'stats': {'PPG': 2.8, 'BPG': 0.2, 'RPG': 3.2}},
                                    'Patterson, Patrick': {'url': 'https://en.wikipedia.org/wiki/Patrick_Patterson_(basketball)', 'stats': {'PPG': 4.9, 'BPG': 0.1, 'RPG': 2.6}},
                                    'Shamet, Landry': {'url': 'https://en.wikipedia.org/wiki/Landry_Shamet', 'stats': {'PPG': 9.3, 'BPG': 0.2, 'RPG': 1.9}},
                                    'Williams, Lou': {'url': 'https://en.wikipedia.org/wiki/Lou_Williams', 'stats': {'PPG': 18.2, 'BPG': 0.2, 'RPG': 3.1}},
                                    'Zubac, Ivica': {'url': 'https://en.wikipedia.org/wiki/Ivica_Zubac', 'stats': {'PPG': 8.3, 'BPG': 0.9, 'RPG': 7.5}}}}}
